basePath: /
definitions:
  handlers.AllApodsResponse:
    properties:
      apods:
        description: List of APODs
        items:
          $ref: '#/definitions/handlers.Apod'
        type: array
      count:
        description: |-
          Total number of APODs found
          example: 15
        type: integer
    type: object
  handlers.Apod:
    properties:
      _id:
        description: |-
          MongoDB ID
          example: 507f1f77bcf86cd799439011
        type: string
      date:
        description: |-
          Date in string format (e.g. "1995-06-16")
          example: 2023-01-15
          format: date
        type: string
      explanation:
        description: |-
          Explanation of the astronomy picture of the day
          example: A beautiful nebula captured by the Hubble telescope
        type: string
      hdurl:
        description: |-
          URL of the high-definition image
          example: https://apod.nasa.gov/apod/image/2301/M31_HubbleSpitzerGendler_960.jpg
          format: uri
        type: string
      media_type:
        description: |-
          Media type (image or video)
          example: image
          enum: image,video
        type: string
      service_version:
        description: |-
          API service version
          example: v1
        type: string
      title:
        description: |-
          Title of the astronomy picture of the day
          example: Andromeda Galaxy
        type: string
      url:
        description: |-
          URL of the standard resolution image
          example: https://apod.nasa.gov/apod/image/2301/M31_HubbleSpitzerGendler_960.jpg
          format: uri
        type: string
    type: object
  handlers.ApodsDateRangeResponse:
    properties:
      apods:
        description: List of APODs
        items:
          $ref: '#/definitions/handlers.Apod'
        type: array
      count:
        description: |-
          Total number of APODs found
          example: 7
        type: integer
    type: object
  handlers.LanguageInfo:
    properties:
      code:
        type: string
      name:
        type: string
      nativeName:
        type: string
    type: object
  handlers.SearchResponse:
    properties:
      page:
        description: |-
          Current page number
          example: 1
        type: integer
      per_page:
        description: |-
          Items per page
          example: 20
        type: integer
      results:
        description: Search results
        items:
          $ref: '#/definitions/handlers.Apod'
        type: array
      total_pages:
        description: |-
          Total number of available pages
          example: 3
        type: integer
      total_results:
        description: |-
          Total number of results found
          example: 42
        type: integer
    type: object
info:
  contact: {}
  description: API for managing NASA APOD (Astronomy Picture of the Day) data
  title: AstroVista API
  version: "1.0"
paths:
  /apod:
    get:
      consumes:
      - application/json
      description: Returns the most recent Astronomy Picture of the Day
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Apod'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get the most recent APOD
      tags:
      - APOD
    post:
      consumes:
      - application/json
      description: Fetches the most recent APOD from NASA API and adds it to the database
      parameters:
      - description: Internal API token
        in: header
        name: X-API-Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Adds new APOD from NASA
      tags:
      - APOD
  /apod/{date}:
    get:
      consumes:
      - application/json
      description: Returns the astronomy picture of the day for the specified date
      parameters:
      - description: Date in YYYY-MM-DD format
        example: '"2023-01-15"'
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Apod'
        "400":
          description: Error getting APOD
          schema:
            additionalProperties: true
            type: object
      summary: Gets an APOD by specific date
      tags:
      - APOD
  /apods:
    get:
      consumes:
      - application/json
      description: Returns all registered Astronomy Pictures of the Day
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AllApodsResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get all APODs
      tags:
      - APODs
  /apods/date-range:
    get:
      consumes:
      - application/json
      description: Returns the Astronomy Pictures of the Day within a specified date
        range
      parameters:
      - description: Start date (YYYY-MM-DD format)
        example: '"2023-01-01"'
        in: query
        name: start
        type: string
      - description: End date (YYYY-MM-DD format)
        example: '"2023-01-31"'
        in: query
        name: end
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ApodsDateRangeResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get APODs by date range
      tags:
      - APODs
  /apods/search:
    get:
      consumes:
      - application/json
      description: Search APODs with filters, pagination and sorting
      parameters:
      - description: Page number
        example: 1
        in: query
        minimum: 1
        name: page
        type: integer
      - description: Items per page (1-200)
        example: 20
        in: query
        maximum: 200
        minimum: 1
        name: perPage
        type: integer
      - description: Media type (image, video or any)
        enum:
        - image
        - video
        - any
        example: image
        in: query
        name: mediaType
        type: string
      - description: Text to search in title and explanation
        example: nebula
        in: query
        name: search
        type: string
      - description: Start date (YYYY-MM-DD format)
        example: "2023-01-01"
        in: query
        name: startDate
        type: string
      - description: End date (YYYY-MM-DD format)
        example: "2023-01-31"
        in: query
        name: endDate
        type: string
      - description: Sort order (asc or desc)
        enum:
        - asc
        - desc
        example: desc
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SearchResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Advanced APOD search
      tags:
      - APODs
  /languages:
    get:
      consumes:
      - application/json
      description: Returns the list of languages supported by the AstroVista API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.LanguageInfo'
            type: array
      summary: List supported languages
      tags:
      - Configuration
swagger: "2.0"
