basePath: /
definitions:
  handlers.AllApodsResponse:
    properties:
      apods:
        description: Lista de APODs
        items:
          $ref: '#/definitions/handlers.Apod'
        type: array
      count:
        description: |-
          Número total de APODs encontrados
          example: 15
        type: integer
    type: object
  handlers.Apod:
    properties:
      _id:
        description: |-
          ID do MongoDB
          example: 507f1f77bcf86cd799439011
        type: string
      date:
        description: |-
          Data no formato string (ex: "1995-06-16")
          example: 2023-01-15
          format: date
        type: string
      explanation:
        description: |-
          Explicação da imagem astronômica do dia
          example: Uma bela nebulosa capturada pelo telescópio Hubble
        type: string
      hdurl:
        description: |-
          URL da imagem em alta definição
          example: https://apod.nasa.gov/apod/image/2301/M31_HubbleSpitzerGendler_960.jpg
          format: uri
        type: string
      media_type:
        description: |-
          Tipo de mídia (imagem ou vídeo)
          example: image
          enum: image,video
        type: string
      service_version:
        description: |-
          Versão do serviço da API
          example: v1
        type: string
      title:
        description: |-
          Título da imagem astronômica do dia
          example: Galáxia de Andrômeda
        type: string
      url:
        description: |-
          URL da imagem em resolução padrão
          example: https://apod.nasa.gov/apod/image/2301/M31_HubbleSpitzerGendler_960.jpg
          format: uri
        type: string
    type: object
  handlers.ApodsDateRangeResponse:
    properties:
      apods:
        description: Lista de APODs
        items:
          $ref: '#/definitions/handlers.Apod'
        type: array
      count:
        description: |-
          Número total de APODs encontrados
          example: 7
        type: integer
    type: object
  handlers.SearchResponse:
    properties:
      page:
        description: |-
          Número da página atual
          example: 1
        type: integer
      perPage:
        description: |-
          Itens por página
          example: 20
        type: integer
      results:
        description: Resultados da busca
        items:
          $ref: '#/definitions/handlers.Apod'
        type: array
      totalPages:
        description: |-
          Total de páginas disponíveis
          example: 3
        type: integer
      totalResults:
        description: |-
          Número total de resultados encontrados
          example: 42
        type: integer
    type: object
info:
  contact: {}
  description: API para gerenciar dados da NASA APOD (Astronomy Picture of the Day)
  title: AstroVista API
  version: "1.0"
paths:
  /apod:
    get:
      consumes:
      - application/json
      description: Retorna a imagem astronômica do dia mais recente
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Apod'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtém o APOD mais recente
      tags:
      - APOD
    post:
      consumes:
      - application/json
      description: Busca na API da NASA o APOD mais recente e adiciona ao banco de
        dados
      parameters:
      - description: Token de API interno
        in: header
        name: X-API-Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Adiciona novo APOD da NASA
      tags:
      - APOD
  /apod/{date}:
    get:
      consumes:
      - application/json
      description: Retorna a imagem astronômica do dia para a data especificada
      parameters:
      - description: Data no formato YYYY-MM-DD
        example: '"2023-01-15"'
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Apod'
        "400":
          description: Erro ao obter APOD
          schema:
            additionalProperties: true
            type: object
      summary: Obtém um APOD por data específica
      tags:
      - APOD
  /apods:
    get:
      consumes:
      - application/json
      description: Retorna todas as imagens astronômicas do dia cadastradas
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AllApodsResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Obtém todos os APODs
      tags:
      - APODs
  /apods/date-range:
    get:
      consumes:
      - application/json
      description: Retorna as imagens astronômicas do dia dentro de um intervalo de
        datas especificado
      parameters:
      - description: Data de início (formato YYYY-MM-DD)
        example: '"2023-01-01"'
        in: query
        name: start
        type: string
      - description: Data de fim (formato YYYY-MM-DD)
        example: '"2023-01-31"'
        in: query
        name: end
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ApodsDateRangeResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Obtém APODs por intervalo de datas
      tags:
      - APODs
  /apods/search:
    get:
      consumes:
      - application/json
      description: Busca APODs com filtros, paginação e ordenação
      parameters:
      - description: Número da página
        example: 1
        in: query
        minimum: 1
        name: page
        type: integer
      - description: Itens por página (1-200)
        example: 20
        in: query
        maximum: 200
        minimum: 1
        name: perPage
        type: integer
      - description: Tipo de mídia (image, video ou any)
        enum:
        - image
        - video
        - any
        example: image
        in: query
        name: mediaType
        type: string
      - description: Texto para busca em título e explicação
        example: nebulosa
        in: query
        name: search
        type: string
      - description: Data inicial (formato YYYY-MM-DD)
        example: "2023-01-01"
        in: query
        name: startDate
        type: string
      - description: Data final (formato YYYY-MM-DD)
        example: "2023-01-31"
        in: query
        name: endDate
        type: string
      - description: Ordenação (asc ou desc)
        enum:
        - asc
        - desc
        example: desc
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SearchResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Pesquisa avançada de APODs
      tags:
      - APODs
swagger: "2.0"
